name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Upgrade pipx
        run: |
          pip install --constraint=.github/workflows/constraints.txt pipx
          pipx --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Initialise git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Detect new version
        uses: Stefansm/nbgv.sh-action@main
        id: version

{% raw %}
      - name: Tag new version
        run: |
          git tag v${{ steps.version.outputs.version }} &&
          git push --tags

      - name: Set version with Poetry
        run: |
          poetry version ${{ steps.version.outputs.version }}

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.10
{% endraw %}
