{% raw %}
name: Tests
on:
  push:
    branches-ignore:
      - main
      - master
  workflow_call: {}
jobs:
  tests:
    name: ${{ matrix.session }} ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.10", os: "ubuntu-latest", session: "mypy" }
          - { python: "3.10", os: "ubuntu-latest", session: "pre-commit" }
          - { python: "3.10", os: "windows-latest", session: "test" }
          - { python: "3.10", os: "macos-latest", session: "test" }
          - { python: "3.10", os: "ubuntu-latest", session: "docs" }

    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4.6.1
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install pipx
        run: |
          pip install --constraint=.github/workflows/constraints.txt pipx
          pipx --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Run Makfile
        run: |
          make ${{ matrix.session }}
{% endraw %}
